### ISSUE TITLE
Cannot connect to EC2 machines - should use PublicIpv4 when available

### ISSUE THREAD

**Issue by GlennS** [kamilchm/nixops-dns#4]
(Sorry for spamming your issues list - I don't even know if you really want to maintain this.)

It seems like it would be better to use publicIpv4 rather than privateIpv4 when available. 

When I deploy an Amazon Ec2 machine, for example, I can't SSH to it using the privateIpv4 value.

I suggest changing:
```
select ra.value from Resources r, ResourceAttrs ra
where r.name = ? and r.id = ra.machine and ra.name = 'privateIpv4'
```

To:
```
select ra.value from Resources r, ResourceAttrs ra
where r.name = ? and r.id = ra.machine and ra.name in ('publicIpv4, 'privateIpv4')
order by ra.name desc
```

**Comment by kamilchm** [comment]
This looks good. I can merge a PR if you want or we can move `nixpkgs` to your fork, cause I don't use it for some time now and I think than an active user can be a better maintainer.

**Comment by GlennS** [comment]
Happy to be the maintainer for this on nixpkgs since you're not using it anymore. I'm using it at work, so can probably spare a little time now and then to keep it nice.

I'll do a little more maintenance on my branch to make my changes less likely to break backwards compatability first.

I'll add a pull request on nixpkgs after that.

**Comment by GlennS** [comment]
Update on this since I obviously didn't do anything.

I've stopped using nixops-dns as well. I've moved to a one-statefile-per-deployment approach, which doesn't fit very well.
